### ISSUE TITLE
Smach viewer not working after messing with wxPython

### ISSUE THREAD

**Issue by JanTromp** [ros-visualization/executive_smach_visualization#25]
Hey everyone,

The smach viewer was working okay but at random moments it would close itself for no reason.
Error being:

> Segmentation fault (core dumped)

At startup i got the message:

> wxversion 2.8 is not installed, installed versions are ['3.0-gtk2']
> wxversion 2.8 is not installed, installed versions are ['3.0-gtk2']

So i thought maybe update this, maybe that will fix it.

so i updated wxPython by (found in this link https://wiki.wxpython.org/How%20to%20install%20wxPython):

> pip install -U \ -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 \wxPython

This downloaded 102 MB of data and installed the following packages:
Pillow, six, wxPython

After that i started the smach viewer again and got the following error:

>  Traceback (most recent call last):
>   File "/home/assembly_project/src/executive_smach_visualization/smach_viewer/scripts/smach_viewer.py", line 77, in <module>
>     from smach_viewer import xdot
>   File "/home/assembly_project/src/executive_smach_visualization/smach_viewer/src/smach_viewer/xdot/__init__.py", line 1, in <module>
>     import wxxdot
>   File "/home/assembly_project/src/executive_smach_visualization/smach_viewer/src/smach_viewer/xdot/wxxdot.py", line 45, in <module>
>     gdkLib = wx.lib.wxcairo._findGDKLib()
> AttributeError: 'module' object has no attribute '_findGDKLib'

Anyone able to help me get this back?

I am not that expecrienced with linux so i dont know what all the commands mean when installing something.
I'm afraid i messed it up and i'm not able to fix this by myself.

If there are any questions or things unclear, feel free to drop a comment.

Kind regards,
Jan Tromp

**Comment by JanTromp** [comment]
update:
So I googled some more and manage to get back to my original situation (I think)

I used sudo apt update and that did the trick.

Still have no idea what happened and what caused the original problem so im gonna leave this open.

This is what my terminal displays when running $ rosrun smach_viewer smach_viewer.py 

> wxversion 2.8 is not installed, installed versions are ['3.0-gtk2']
> wxversion 2.8 is not installed, installed versions are ['3.0-gtk2']

> (smach_viewer.py:11708): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

_Here my smach viewer does work, but after a while it gives the following_

> Segmentation fault (core dumped)
